#!/bin/bash
#for NFS-SERVER setup



yum install -y git
#cd /tmp
#git clone https://github.com/nic-instruction/hello-nti-310.git

## added thurs2/6/20
yum install -y nfs-utils
mkdir /var/nfsshare
mkdir /var/nfsshare/devstuff
mkdir /var/nfsshare/testing
mkdir /var/nfsshare/home_dirs
chmod -R 777 /var/nfsshare/
systemctl enable rcpbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap
cd /var/nfsshare/

echo "/var/nfsshare/home_dirs *(rw,sync,no_all_squash)
/var/nfsshare/devstuff  *(rw,sync,no_all_squash)
/var/nfsshare/testing   *(rw,sync,no_all_squash)" >> /etc/exports

systemctl restart nfs-server
#install net tools to get ifconfig
yum -y install net-tools
yum -y install openldap-servers openldap-clients

cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG 
chown ldap. /var/lib/ldap/DB_CONFIG

systemctl enable slapd
systemctl start slapd

yum -y install httpd
yum -y install phpldapadmin
# some source editing
# Tell SE linux what's going on, so that it doesn't freek
setsebool -P httpd_can_connect_ldap on

systemctl enable httpd
systemctl start httpd

sed -i 's,Require local,#Require local\n    Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf

# decent config guide: http://www.itzgeek.com/how-tos/linux/centos-how-tos/install-configure-phpldapadmin-centos-7-ubuntu-16-04.html
#from >>> Hello-NTI-310-2020/config/Eli_LDAP.sh <<<< 2/13
unalias cp
cp /etc/phpldapadmin/config.php /etc/phpldapadmin/config.php.orig	# make a copy of the origonal config file, we need the blowfish key
grep 'config.*blowfish' /etd/phpldapadmin/config.php.orig		# grep for the blowfish key so we can see it in the logs
rightkey=$( grep 'config.*blowfish' /etc/phpldapadmin/config.php.orig )	# use some rejex to get just the key and shove it into the variable 'right key'
cp /tmp/hello-nti-310/config/config.php /etc/phpldapadmin/config/php	# copy our pre-made config to config.php

sed -i "s/\$config->custom->session/['blowfish'\] = '6ad4614a51893aaf046e2057e7870ae4'\;  # Autogenerated for ldap-c/$rightkey/g" /etc/phpldapadmin/config.php # fix
the key
chown ldap:apache /etc/phpldapadmin/config.php

systemctl restart httpd



